networks:
  servers:

services:
  balancer:
    build: .
    command: 'lb'
    networks:
      - servers
    ports:
      - '8090:8090'
    depends_on:
      - server1
        # condition: service_healthy
      - server2
        # condition: service_healthy
      - server3
        # condition: service_healthy

  db:
    build: .
    command: 'db'
    networks:
      - servers
    ports:
      - '8083:8080'
    healthcheck:
      test: ['CMD', 'pgrep', 'db']
      interval: 2s
      retries: 5
      start_period: 5s

  server1:
    build: .
    networks:
      - servers
    ports:
      - '8080:8080'
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 15s

    depends_on:
      db:
        condition: service_healthy

  server2:
    build: .
    networks:
      - servers
    ports:
      - '8081:8080'
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 15s

    depends_on:
      db:
        condition: service_healthy

  server3:
    build: .
    networks:
      - servers
    ports:
      - '8082:8080'
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 15s

    depends_on:
      db:
        condition: service_healthy
