version: '3.8'

services:
  db:
    build: .
    command: db
    ports: ['8081:8081']
    volumes: ['./out:/opt/practice-4/out']
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8081/db/health']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks: [servers]

  server1:
    build: .
    command: server
    environment: ['PORT=8080']
    depends_on: [db]
    networks: [servers]

  server2:
    build: .
    command: server
    environment: ['PORT=8080']
    depends_on: [db]
    networks: [servers]

  server3:
    build: .
    command: server
    environment: ['PORT=8080']
    depends_on: [db]
    networks: [servers]

  balancer:
    build: .
    command: lb
    ports: ['8090:8090']
    depends_on: [server1, server2, server3]
    networks: [servers]

networks:
  servers:
    driver: bridge
